[package]
name = "poc-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polkavm = { workspace = true }

[features]
default = ["std"]
std = [
    "polkavm/std",
]
